[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "payrix-py-mcp-server"
version = "0.1.0"
description = "MCP Server for Payrix"
requires-python = ">=3.10"